-- Config_TableSources

WITH ctePPMDWConfig_TableSources AS
(
SELECT
	TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME	
	, [SOURCE_TABLE] = RIGHT(TABLE_NAME, LEN(TABLE_NAME) - CHARINDEX('_',TABLE_NAME))
	, [STAGE_TABLEPREFIX] = LEFT(TABLE_NAME, CHARINDEX('_',TABLE_NAME))
FROM
  PPMDW.INFORMATION_SCHEMA.TABLES
WHERE 
	table_type = 'BASE TABLE'
	AND TABLE_SCHEMA = 'stage'
)

SELECT 
	TABLE_CATALOG
	, TABLE_SCHEMA
	, SOURCE_TABLE	
	, STAGE_TABLEPREFIX
	, [TARGET_TABLE] = TABLE_NAME
INTO stage.Config_TableSources
FROM ctePPMDWConfig_TableSources
WHERE [STAGE_TABLEPREFIX] NOT IN ('Config_', '')

