CREATE TABLE [stage].[GMENU_CONCEPT]
(
	[CONCEPTCODE]     VARCHAR(20)   NOT NULL, 
	[NAME]            VARCHAR(40)   NULL, 
	[SALESCHANNELID]  NUMERIC(8, 0) NULL, 
	[CAPTAINID]       NUMERIC(8, 0) NULL, 
	[PRICETYPEID]     NUMERIC(8, 0) NULL, 
	[CUSTOMERGROUPID] NUMERIC(8, 0) NULL, 
	[PRODUCTCODE]     VARCHAR(12)   NULL, 
	[CUSTOMER]        VARCHAR(9)    NULL, 
	[DRIVER_CODE]     NUMERIC(5, 0) NULL, 
	[CORE_CODE]       NUMERIC(5, 0) NULL, 
	[STATUSTYPE]      CHAR(1)       NULL, 
	Id_AzCluster      INT NOT NULL IDENTITY CONSTRAINT [PkAzCluster_GMENU_CONCEPT] PRIMARY KEY CLUSTERED
)
 