CREATE TABLE [dbo].[GMENU_SALESPERSON] (
    [SLPRSN_CODE]      VARCHAR (3)  NOT NULL,
    [CLIENT_CODE]      VARCHAR (10) NULL,
    [LOC_TYPE]         VARCHAR (1)  NOT NULL,
    [STATUS_TYPE]      VARCHAR (1)  NOT NULL,
    [LAST_NAME]        VARCHAR (15) NOT NULL,
    [FIRST_NAME]       VARCHAR (14) NOT NULL,
    [MIDDLE_INIT]      VARCHAR (1)  NULL,
    [SALES_DEPT_CODE]  VARCHAR (3)  NOT NULL,
    [SALESMAN]         NUMERIC (4)  NOT NULL,
    [FOODSERVICE_FLAG] VARCHAR (1)  NOT NULL
);

