CREATE TABLE [dbo].[GMENU_PROD_CLASS] (
    [PROD_CLASS_CODE] VARCHAR (6)  NOT NULL,
    [DESCR]           VARCHAR (30) NOT NULL,
    [PAY_TERM_CODE]   VARCHAR (2)  NOT NULL,
    [DATE_TERM_TYPE]  CHAR (1)     NOT NULL
);

