CREATE TABLE [stage].[GMENU_MKT_TERRITORY] (
    [MKT_TERR_CODE] VARCHAR (3)  NOT NULL,
    [DESCR]         VARCHAR (30) NOT NULL,
    [MKT_RGN_CODE]  VARCHAR (3)  NOT NULL,
	Id_AzCluster    INT          NOT NULL IDENTITY 
	CONSTRAINT [PkAzCluster_GMENU_MKT_TERRITORY] PRIMARY KEY CLUSTERED
);

