CREATE TABLE [stage].[GMENU_PROD_GROUP] (
    [PROD_GROUP_CODE] VARCHAR (6)  NOT NULL,
    [DESCR]           VARCHAR (30) NOT NULL,
	Id_AzCluster      INT          NOT NULL IDENTITY 
	CONSTRAINT [PkAzCluster_GMENU_PROD_GROUP] PRIMARY KEY CLUSTERED
);

