CREATE TABLE [stage].[GMENU_PRESERVATION_TYPE] (
    [PRES_TYPE_CODE] NUMERIC (2)  NOT NULL,
    [DESCR]          VARCHAR (30) NOT NULL,
	Id_AzCluster     INT          NOT NULL IDENTITY 
	CONSTRAINT [PkAzCluster_GMENU_PRESERVATION_TYPE] PRIMARY KEY CLUSTERED
);

