CREATE TABLE [stage].[GMENU_PROD_CATEGORY] (
    [PROD_CAT_CODE]        VARCHAR (6)  NOT NULL,
    [DESCR]                VARCHAR (30) NOT NULL,
    [MARKET_GRP_CODE]      VARCHAR (4)  NULL,
    [SALES_CR_COMPANY]     NUMERIC (4)  NULL,
    [SALES_CR_ACCT_UNIT]   CHAR (15)    NULL,
    [SALES_CR_ACCOUNT]     NUMERIC (6)  NULL,
    [SALES_CR_SUB_ACCOUNT] NUMERIC (4)  NULL,
	Id_AzCluster           INT          NOT NULL IDENTITY 
	CONSTRAINT [PkAzCluster_GMENU_PROD_CATEGORY] PRIMARY KEY CLUSTERED
);

