CREATE TABLE [stage].[GMENU_CALENDAR] (
    [CAL_TYPE]         CHAR (1)      NOT NULL,
    [YEAR]             NUMERIC (4)   NULL,
    [QUARTER]          NUMERIC (1)   NULL,
    [MONTH]            NUMERIC (2)   NULL,
    [WEEK]             NUMERIC (2)   NULL,
    [JULIAN_DAY]       NUMERIC (3)   NULL,
    [CAL_DATE]         DATETIME2 (7) NULL,
    [YEAR_BEG_DATE]    DATETIME2 (7) NULL,
    [YEAR_END_DATE]    DATETIME2 (7) NULL,
    [QUARTER_BEG_DATE] DATETIME2 (7) NULL,
    [QUARTER_END_DATE] DATETIME2 (7) NULL,
    [MONTH_BEG_DATE]   DATETIME2 (7) NULL,
    [MONTH_END_DATE]   DATETIME2 (7) NULL,
    [WEEK_BEG_DATE]    DATETIME2 (7) NULL,
    [WEEK_END_DATE]    DATETIME2 (7) NULL,
	Id_AzCluster       INT           NOT NULL IDENTITY 
	CONSTRAINT [PkAzCluster_GMENU_CALENDAR] PRIMARY KEY CLUSTERED
);
