CREATE TABLE [stage].[GMENU_TREATMENT]
(
	[TREATMENT_CODE] VARCHAR(2) NOT NULL , 
    [DESCR] VARCHAR(30) NULL, 
    [MEDICINE_TYPE] VARCHAR(7) NULL, 
    CONSTRAINT [PK_TREATMENT] PRIMARY KEY ([TREATMENT_CODE])
)
