CREATE TABLE [stage].[GMENU_MKT_REGION] (
    [MKT_RGN_CODE] VARCHAR (3)  NOT NULL,
    [DESCR]        VARCHAR (30) NOT NULL,
	Id_AzCluster   INT          NOT NULL IDENTITY 
	CONSTRAINT [PkAzCluster_GMENU_MKT_REGION] PRIMARY KEY CLUSTERED
);

