CREATE TABLE [stage].[GMENU_CUSTOMER_CHANNEL] (
    [CUST_CHANL_CODE] VARCHAR (3)  NOT NULL,
    [DESCR]           VARCHAR (30) NOT NULL,
	Id_AzCluster      INT          NOT NULL IDENTITY 
	CONSTRAINT [PkAzCluster_GMENU_CUSTOMER_CHANNEL] PRIMARY KEY CLUSTERED
);

