CREATE TABLE [stage].[GMENU_CUSTOMER_GROUP] (
    [CUST_GROUP_CODE] VARCHAR (6)  NOT NULL,
    [NAME]            VARCHAR (30) NOT NULL,
    [CUST_GROUP_TYPE] CHAR (1)     NOT NULL,
	Id_AzCluster      INT          NOT NULL IDENTITY 
	CONSTRAINT [PkAzCluster_GMENU_CUSTOMER_GROUP] PRIMARY KEY CLUSTERED
);

