CREATE TABLE [stage].[GMENU_BUYER_CLASS] (
    [BUYER_CLASS_CODE] VARCHAR (6)  NOT NULL,
    [DESCR]            VARCHAR (30) NOT NULL,
	Id_AzCluster       INT          NOT NULL IDENTITY 
	CONSTRAINT [PkAzCluster_GMENU_BUYER_CLASS] PRIMARY KEY CLUSTERED
);

