CREATE TABLE [stage].[GMENU_BRAND] (
    [BRAND_CODE] VARCHAR (3)  NOT NULL,
    [NAME]       VARCHAR (30) NOT NULL,
	Id_AzCluster INT          NOT NULL IDENTITY 
	CONSTRAINT [PkAzCluster_GMENU_BRAND] PRIMARY KEY CLUSTERED
);

