CREATE TABLE [stage].[GMENU_WOG_SIZE] (
    [WOG_SIZE_CODE] VARCHAR (10)   NOT NULL,
    [MIN_DROP_WGT]  NUMERIC (8, 4) NOT NULL,
    [MAX_DROP_WGT]  NUMERIC (8, 4) NOT NULL,
	Id_AzCluster    INT            NOT NULL IDENTITY 
	CONSTRAINT [PkAzCluster_GMENU_WOG_SIZE] PRIMARY KEY CLUSTERED
);

