CREATE TABLE [stage].[GMENU_COUNTRY] (
    [COUNTRY_CODE]      VARCHAR (3)  NOT NULL,
    [NAME]              VARCHAR (40) NOT NULL,
    [EXPORT_ID]         VARCHAR (3)  NULL,
    [LAWSON_CNTRY_CODE] VARCHAR (2)  NULL
);

