CREATE TABLE [stage].[GMENU_PROD_LINE] (
    [PROD_LINE_CODE] CHAR (6)  NOT NULL,
    [DESCR]          CHAR (30) NOT NULL,
	Id_AzCluster     INT       NOT NULL IDENTITY 
	CONSTRAINT [PkAzCluster_GMENU_PROD_LINE] PRIMARY KEY CLUSTERED
);

