CREATE TABLE [stage].[GMENU_BIRD_SIZE] (
    [BIRD_SIZE_CODE] VARCHAR (2)  NOT NULL,
    [DESCR]          VARCHAR (30) NOT NULL,
	Id_AzCluster     INT          NOT NULL IDENTITY 
	CONSTRAINT [PkAzCluster_GMENU_BIRD_SIZE] PRIMARY KEY CLUSTERED
);

