CREATE TABLE [stage].[GMENU_COMPANY] (
    [COMP_CODE]        NUMERIC (4)  NOT NULL,
    [NAME]             VARCHAR (40) NOT NULL,
    [ADDR1]            VARCHAR (30) NULL,
    [ADDR2]            VARCHAR (30) NULL,
    [ADDR3]            VARCHAR (30) NULL,
    [CITY]             VARCHAR (25) NULL,
    [STATE_CODE]       VARCHAR (2)  NULL,
    [COUNTRY_CODE]     VARCHAR (3)  NOT NULL,
    [ZIP_POSTAL]       VARCHAR (10) NULL,
    [STATE_PROVINCE]   VARCHAR (30) NULL,
    [FG_RPT_COMP_CODE] NUMERIC (4)  NULL,
    [GO_RPT_COMP_CODE] NUMERIC (4)  NULL,
    [SC_RPT_COMP_CODE] NUMERIC (4)  NULL,
    CONSTRAINT [PK_GMENU_COMPANY] PRIMARY KEY CLUSTERED ([COMP_CODE] ASC)
);

