CREATE TABLE [dbo].[GMENU_HOUSE] (
    [GROWER_CODE]                NUMERIC (5)    NOT NULL,
    [FARM_CODE]                  NUMERIC (2)    NOT NULL,
    [HOUSE_CODE]                 NUMERIC (2)    NOT NULL,
    [NAME]                       VARCHAR (30)   NOT NULL,
    [SORT_NAME]                  VARCHAR (30)   NOT NULL,
    [ADDR1]                      VARCHAR (30)   NULL,
    [ADDR2]                      VARCHAR (30)   NULL,
    [ADDR3]                      VARCHAR (30)   NULL,
    [CITY]                       VARCHAR (25)   NULL,
    [STATE_CODE]                 VARCHAR (2)    NULL,
    [STATE_PROVINCE]             VARCHAR (30)   NULL,
    [COUNTRY_CODE]               VARCHAR (3)    NOT NULL,
    [ZIP_POSTAL]                 VARCHAR (10)   NULL,
    [COUNTY_CODE]                VARCHAR (2)    NULL,
    [COMP_CODE]                  NUMERIC (4)    NOT NULL,
    [PHONE_NBR1]                 VARCHAR (15)   NULL,
    [PHONE_NBR2]                 VARCHAR (15)   NULL,
    [PAGER_NBR]                  VARCHAR (15)   NULL,
    [FAX_NBR]                    VARCHAR (15)   NULL,
    [STATUS_TYPE]                VARCHAR (1)    NOT NULL,
    [SQUARE_FEET]                NUMERIC (7)    NOT NULL,
    [DEF_CLIENT_CODE]            VARCHAR (10)   NOT NULL,
    [DEF_SRVCPRSN_CODE]          VARCHAR (3)    NULL,
    [DEF_FEED_CNSMP_FCT]         NUMERIC (3, 2) NOT NULL,
    [DEF_FLOCK_TYPE_CODE]        VARCHAR (3)    NOT NULL,
    [DEF_FEED_AUTO_FLAG]         VARCHAR (1)    NOT NULL,
    [STAGES]                     NUMERIC (1)    NOT NULL,
    [HOUSE_TYPE_CODE]            VARCHAR (2)    NOT NULL,
    [FEED_SPEC_DELV_INSTR]       VARCHAR (50)   NULL,
    [FEED_DRCTN_TO_HOUSE]        VARCHAR (50)   NULL,
    [FEED_TANDEM_ONLY_FLAG]      VARCHAR (1)    NOT NULL,
    [CYCLES_PER_YEAR]            NUMERIC (5, 2) NOT NULL,
    [FEED_DELV_SCHG_CODE]        NUMERIC (2)    NULL,
    [DEPOP_DATE]                 DATETIME2 (7)  NULL,
    [TUNNEL_VENT_ELIG_FLAG]      VARCHAR (1)    NOT NULL,
    [TUNNEL_VENT_EFF_DATE]       DATETIME2 (7)  NULL,
    [TUNNEL_VENT_SETL_NBR]       NUMERIC (2)    NOT NULL,
    [TUNNEL_VENT_PAY_PER_LB]     NUMERIC (4, 4) NOT NULL,
    [NEW_HOUSE_GUAR_ELIG_FLAG]   VARCHAR (1)    NOT NULL,
    [NEW_HOUSE_GUAR_EFF_DATE]    DATETIME2 (7)  NULL,
    [NEW_HOUSE_GUAR_SETL_NBR]    NUMERIC (2)    NOT NULL,
    [NEW_HOUSE_GUAR_PAY_PER_LB]  NUMERIC (4, 4) NOT NULL,
    [DIRECTIONS_TEXT]            VARCHAR (1000) NULL,
    [MIN_VENT_ELIG_FLAG]         VARCHAR (1)    NOT NULL,
    [COMPANY_GAS_FLAG]           VARCHAR (1)    NOT NULL,
    [INACTIVE_DATE]              DATETIME2 (7)  NULL,
    [PULLET_PAY_BASIS_TYPE]      VARCHAR (1)    NOT NULL,
    [FEED_SYSTEM_ELIG_FLAG]      VARCHAR (1)    NOT NULL,
    [FEED_SYSTEM_PAY_PER_LB]     NUMERIC (4, 4) NOT NULL,
    [ART_LIGHT_ELIG_FLAG]        VARCHAR (1)    NOT NULL,
    [ART_LIGHT_PAY_PER_LB]       NUMERIC (4, 4) NOT NULL,
    [DEF_PLANT_CODE]             VARCHAR (2)    NULL,
    [PROPANE_CODE]               VARCHAR (6)    NULL,
    [DEF_FEED_MILL_CODE]         VARCHAR (2)    NULL,
    [MTECH_GROWER_FARM_CODE]     VARCHAR (7)    NULL,
    [BASE_PAY_TYPE]              CHAR (1)       NOT NULL,
    [PREMIUM_BREEDER_FLAG]       CHAR (1)       NOT NULL,
    [FOUR_FLOCK_FLAG]            CHAR (1)       NOT NULL,
    [PREM_TNNL_CONV_FLAG]        CHAR (1)       NOT NULL,
    [PREM_TNNL_CONV_EFF_DATE]    DATETIME2 (7)  NULL,
    [PREM_TNNL_CONV_SETL_NBR]    NUMERIC (2)    NOT NULL,
    [PREM_TNNL_CONV_ADDL_PAY_LB] NUMERIC (4, 4) NOT NULL,
    [TYSON_CONTRACT_FLAG]        CHAR (1)       NOT NULL,
    [EGG_BASE_PAY_TYPE]          VARCHAR (1)    NULL
);

