CREATE TABLE [stage].[SigmaGCT_Product] (
	[ProductID]                   INT           NOT NULL,
	[VendorID]                    INT           NULL,
	[SKU]                         nvarchar(25)  NULL,
	[ProductMasterID]             INT           NULL,
	[refProductMeasurementID]     INT           NULL,
	[Name]                        nvarchar(50)  NULL,
	[Description]                 nvarchar(75)  NULL,
	[CodeValue]                   INT           NULL,
	[CodeText]                    nvarchar(50)  NULL,
	[Comment]                     nvarchar(200) NULL,
	[Sequence]                    INT           NULL,
	[CreatedTime]                 DATETIME      NULL,
	[CreatedByUserID]             INT           NULL,
	[LastModified]                DATETIME      NULL,
	[LastUserID]                  INT           NULL,
	[IsReserved]                  BIT           NULL,
	[IsInactive]                  BIT           NULL,
	[refStatusID]                 INT           NULL,
	[refTypeID]                   INT           NULL,
	[refCategoryID]               INT           NULL,
	[IsBulk]                      BIT           NULL,
	[LoadSequence]                INT           NULL,
	[AverageWeight]               NUMERIC(6, 2) NULL,
	[refUnitOfMeasureID]          INT           NULL,
	[AveragePieceCount]           INT           NULL,
	[ParentProductID]             INT           NULL,
	[refWeightTypeID]             INT           NULL,
	[Price]                       MONEY         NULL,
	[DefaultPalletQuantityToScan] INT           NULL,
	[refProductTypeId]            INT           NULL,
	[PistolaQty]                  INT           NULL,
	[ShortDescr]                  nvarchar(16)  NULL,
	[Cust_Prod_Descr]             VARCHAR(60)   NULL,
	[LineId]                      INT           NULL,
	[DateSellOfs]                 INT           NULL,
	Id_AzCluster                  INT           NOT NULL IDENTITY 
	CONSTRAINT [PkAzCluster_SigmaGCT_Product] PRIMARY KEY CLUSTERED
)
