CREATE TABLE [dbo].[SigmaGCT_OutboundOrderDetail](
	[OutboundOrderDetailID] [int] NOT NULL,
	[OutboundOrderID] [int] NULL,
	[ProductID] [int] NULL,
	[LineNum] [int] NULL,
	[Qty] [int] NULL,
	[Weight] [numeric](12, 2) NULL,
	[IsSplit] [bit] NULL,
	[PONumber] [nvarchar](50) NULL,
	[IsSubstitute] [bit] NULL,
	[AllowOverFill] [bit] NULL,
	[AllowUnderFill] [bit] NULL,
	[OverFillPerc] [numeric](6, 2) NULL,
	[UnderFillPerc] [numeric](6, 2) NULL,
	[MaxOverFillQty] [int] NULL,
	[MinUnderFillQty] [int] NULL,
	[FillStartTime] [datetime] NULL,
	[FillCompleteTime] [datetime] NULL,
	[MarkedForDelete] [bit] NULL,
	[Name] [nvarchar](50) NULL,
	[Description] [nvarchar](75) NULL,
	[CodeValue] [int] NULL,
	[CodeText] [nvarchar](50) NULL,
	[Comment] [nvarchar](200) NULL,
	[Sequence] [int] NULL,
	[CreatedTime] [datetime] NULL,
	[CreatedByUserID] [int] NULL,
	[LastModified] [datetime] NULL,
	[LastUserID] [int] NULL,
	[IsReserved] [bit] NULL,
	[IsInactive] [bit] NULL,
	[refStatusID] [int] NULL,
	[refTypeID] [int] NULL,
	[refCategoryID] [int] NULL,
	[Price] [numeric](6, 2) NULL,
	[refBoxTypeID] [int] NULL,
	[refUnitOfMeasureID] [int] NULL,
	[SAP_MATERIAL_NUM] [nvarchar](10) NULL,
	[Pieces] [int] NULL,
	[CustomerID] [int] NULL,
	[IsConsoleUpdate] [bit] NULL,
	[YUM_LABEL_FLAG] [char](1) NULL,
	[CheckDate] [int] NULL,
	[DateMax] [int] NULL,
	[ProductDateValidationDaysEnabled] [bit] NULL,
	[ProductDateValidationDaysValue] [int] NULL,
	[ProductDateValidationFifoEnabled] [bit] NULL
) ON [PRIMARY]
